name: Build and deploy
env:
  NAME_LogicApp:  ${{vars.LogicApp_Name}}  
  LogicApp_NAME_RG: ${{vars.LogicApp_RG_Name}}
  #AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{vars.AZURE_FUNCTIONAPP_PACKAGE_PATH}}
  #FUNCAPP_PUBLISHPROFILE: ${{secrets.FUNCAPP_PUBLISHPROFILE}}
  #AZURE_LOGIN: ${{secrets.AZURE_LOGIN}}
  DOTNET_VERSION: ${{vars.DOTNET_VERSION}}
  LOGICAPP_PUBLISHPROFILE: ${{secrets.LOGICAPP_PUBLISHPROFILE}}

on:
  workflow_dispatch:
  
#   pull_request:

#     branches: [ "main" ]
    
    
  # push:
  #   branches: [ "main" ]
  #   paths: 
  #     - 'Src/LogicApps/**'

jobs:
  logicappbuild:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Build and upload Artifacts
      uses: "./build/"
      
  logicappdeploydev:
      name: Deploy dev
      runs-on:  ubuntu-latest
      needs: [logicappbuild]
      environment: dev
      steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{secrets.AZURE_LOGIN}}
      - name: Deploy
        uses: "./deploy/"
        with:
          rg_name: ${{env.LogicApp_NAME_RG}}
          fa_name: ${{env.NAME_LogicApp}}
      
         
  
